#-------------------------------
# General Site Settings

menu:
- {name: 'Esculturas', url: ''}
# - {name: 'Blog', url: 'pages/blog.html'}
- {name: 'Sobre', url: 'pages/about.html'}
- {name: 'Contato', url: 'pages/contact.html'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Portfolio com criações e esculturas do artista Maicon Jesus'
  rel-author: 'https://www.instagram.com/zignorante/'
  rel-publisher: 'https://www.instagram.com/zignorante/'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: ''

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'zignorant'

#-------------------------------
# About Section

about: >
  # Sobre

  Profissional de escultura tradicional em plastilina, epóxi bicomponente e cera.
  Atualmente aluno de Artes visuais na Universidade de Brasilia.

contact: >
  # Contato

  - (61) 982450490
  - https://instagram.com/deusexmaico
  - maiconcostaj14@gmail.com

#-------------------------------
# Work Section

projects:
# - {name: 'Project One',        folder: 'proj-1',     file: 'projects/proj-1.html'}
# - {name: 'Project Two',        folder: 'proj-2',     file: 'projects/proj-2.html'}
# - {name: 'Project Three',      folder: 'proj-3',     file: 'projects/proj-3.html'}
# - {name: 'Project Four',       folder: 'proj-4',     file: 'projects/proj-4.html'}
# - {name: 'Project Five',       folder: 'proj-5',     file: 'projects/proj-5.html'}
- {name: 'Justiça',                          folder: 'justica',    file: 'projects/justica.html'}
- {name: 'Dança Involuntaria, Desistencia', folder: 'almoco',     file: 'projects/almoco.html'}
- {name: 'Digimon',                          folder: 'digimon',    file: 'projects/digimon.html'}
- {name: 'Segurança',                        folder: 'seguranca',  file: 'projects/seguranca.html'}
- {name: 'Sucubus',                          folder: 'sucubus',    file: 'projects/sucubus.html'}
- {name: 'A culpa da Vitima',                folder: 'culpa',      file: 'projects/culpa.html'}
- {name: 'Charizard X MewTwo',               folder: 'char',       file: 'projects/char.html'}
- {name: 'Mula Sem Cabeça',                  folder: 'mula',       file: 'projects/mula.html'}
- {name: 'Humanidade',                       folder: 'humanidade', file: 'projects/humanidade.html'}

#-------------------------------
# Contact Section

social:
- {icon: 'twitter', link: 'instagram.com/deusexmaico'}
- {icon: 'facebook', link: '#'}
- {icon: 'instagram', link: '#'}
- {icon: 'github', link: '#'}
- {icon: 'linkedin', link: '#'}
- {icon: 'behance', link: '#'}
- {icon: 'envelope', link: 'mailto:maiconcostaj14@gmail.com'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' / 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
